services:
  nats:
    image: bitnami/nats:2.9.21
    healthcheck:
      # How to do a http request without curl or wget
      test: ["CMD-SHELL", "bash -c 'exec 3<> /dev/tcp/localhost/8222 && echo -e \"GET /healthz HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n\" >&3 && cat <&3 | head -1 | grep -q 200'"]
      interval: 1s
      timeout: 2s
      retries: 20
    volumes:
      - ./nats-server.conf:/opt/bitnami/nats/conf/nats-server.conf:ro
    networks:
      leafnode:
      nats:
  responder-nats:
    build: go-client/
    depends_on:
      nats:
        condition: service_healthy
    environment:
      NATS_CLIENT_TYPE: responder
      NATS_HOST: nats://responder:secret-responder@nats
      NATS_SUBJECT: things.>
    healthcheck:
      test: ["CMD-SHELL", "pgrep client"]
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      nats:
  requester-nats:
    build: go-client/
    depends_on:
      nats:
        condition: service_healthy
      responder-nats:
        condition: service_healthy
    environment:
      NATS_CLIENT_TYPE: requester
      NATS_HOST: nats://requester:secret-requester@nats
      NATS_SUBJECT: things.one
    networks:
      nats:
  leafnode:
    image: bitnami/nats:2.9.21
    depends_on:
      nats:
        condition: service_healthy
    environment:
      NATS_ACCOUNT: Responder
      NATS_HOST: ws://responder:secret-responder@nats:8080
    healthcheck:
      # How to do a http request without curl or wget
      test: ["CMD-SHELL", "bash -c 'exec 3<> /dev/tcp/localhost/8222 && echo -e \"GET /healthz HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n\" >&3 && cat <&3 | head -1 | grep -q 200'"]
      interval: 1s
      timeout: 2s
      retries: 20
    networks:
      leafnode:
      nats:
    volumes:
      - ./leafnode.conf:/opt/bitnami/nats/conf/nats-server.conf:ro
  responder-leafnode:
    build: go-client/
    depends_on:
      leafnode:
        condition: service_healthy
    environment:
      NATS_CLIENT_TYPE: responder
      NATS_HOST: nats://leafnode
      NATS_SUBJECT: things.>
    healthcheck:
      test: ["CMD-SHELL", "pgrep client"]
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      leafnode:
  requester-leafnode:
    build: go-client/
    depends_on:
      nats:
        condition: service_healthy
      responder-leafnode:
        condition: service_healthy
    environment:
      NATS_CLIENT_TYPE: requester
      NATS_HOST: nats://requester:secret-requester@nats
      NATS_SUBJECT: things.one
    networks:
      nats:
networks:
  nats:
  leafnode:
